#+title: Readme

* Intro

Test with FreeEEG32 board to verify sample-rate

* Measurement description

On channel 1 a 40Hz signal is recorded via cross-over (generated by VHP device), noticeable as a 80Hz signal. 50Hz main is present.

* Why

When using Brainflow to record EEG measurements we assume a fixed 512Hz sample rate. We noticed that the timestamp recorded by Brainflow varies and were wondering that in some cases it might be more precise that 512Hz assumption.

These folder contains tests to verify the assumption.

* Results

** ODS

See the ODS files for manual verification

** viz1.py

The ~-i~ or ~--interpolate~ option was added to the viz1.py script from =basic-visualization=

Without interpolation, see =noInterpolation.png=:
#+begin_src bash
$ python viz1.py  -c config-calibration.yaml  -f 251108-2228_FREEEEG32_BOARD_baseline_with_VHP_powered_ON_stim_ON_no_contact.csv.xz 
#+end_src



With interpolation, see =Interpolation.png=:
#+begin_src bash
$ python viz1.py  -c config-calibration.yaml  -f 251108-2228_FREEEEG32_BOARD_baseline_with_VHP_powered_ON_stim_ON_no_contact.csv.xz -i
#+end_src



* Conclusion

When reading out a Mentalab device with Brainflow (EXPLORE_8_CHAN_BOARD) the sample rate is rather variable and needs interpolation. For the FreeEEG32 this is not the case. It's better to stick with the fixed 512Hz sampling rate. Interpolation is not needed and creates artifacts. 






